---
image:
  repository: ghcr.io/archway-network/lambo-proxy
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podSecurityContext:
  fsGroup: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: false

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  port: 8080
  type: ClusterIP

serviceMonitor:
  enabled: false
  additionalLabels: {}
  interval: 1m
  scrapeTimeout: 10s
  metricsPath: /metrics
  targetLabels: []
  metricRelabelings: []
  relabelings: []

ingress:
  enabled: true
  className: ""
  annotations: {
    cert-manager.io/cluster-issuer: letsencrypt-prod-kong
  }
  hosts:
    - host: rpc.osmosis.lambo.archway.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: rpc-osmosis-lambo-tls
      hosts:
        - rpc.osmosis.lambo.archway.io

config: |
  # Load Balancer Configuration
  # Environment variables override these values

  # Port on which the load balancing proxy listens
  proxy_port: 8080

  # Interval between health check cycles
  health_check_interval: 5s

  # Number of consecutive failures before marking an endpoint as unhealthy
  health_check_failures: 3

  # EWMA (Exponentially Weighted Moving Average) decay factor (0.1 = slow memory)
  ewma_alpha: 0.1

  # List of backend RPC endpoints to load balance
  backend_addresses:
    - "rpc-osmosis.ecostake.com:443"
    - "osmosis-rpc.polkachu.com:443"
    - "rpc.osmosis.validatus.com:443"
